application: selfstudy
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/ali.png
- url: /static/(.*)
  static_files: static/\1
- url: /.*
  wsgi_app: application:app
